"""
Generates SecretsBridge_generated.h from environment secrets.

Run at build time (pre-CMake or from Gradle). Reads ADDON_CLIENT_SECRET,
and securely binds it against the release keystore's SHA-256 certificate fingerprint.
The secret is double-encrypted using a keystream derived from the signing certificate
itself, so that the secret CANNOT be recovered without the genuine release keystore.

Usage:
    python tools/generate_native_secrets.py
"""

import base64
import hashlib
import hmac
import os
import random


def resolve_env(name: str) -> str:
    val = os.environ.get(name, "").strip()
    if val:
        return val
    if os.path.isfile(".env"):
        with open(".env", "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith(f"{name}="):
                    return line.split("=", 1)[1].strip()
    return ""


def resolve_cert_sha256() -> str:
    env_cert = resolve_env("RELEASE_CERT_SHA256")
    if env_cert:
        return env_cert.strip().lower()

    b64_key = resolve_env("SIGNING_KEY")
    passwords = [
        resolve_env("KEY_STORE_PASSWORD"),
        resolve_env("RELEASE_STORE_PASSWORD"),
        resolve_env("KEY_PASSWORD"),
        resolve_env("RELEASE_KEY_PASSWORD"),
        "3w6gLAaDj0oTcTxHNkRk",
        "",
    ]
    if b64_key:
        try:
            der = base64.b64decode(b64_key.strip())
            from cryptography.hazmat.primitives.serialization import pkcs12
            from cryptography.hazmat.primitives import hashes
            for pw in passwords:
                try:
                    p12 = pkcs12.load_key_and_certificates(der, pw.encode("utf-8") if pw else None)
                    cert = p12[1]
                    if cert:
                        return cert.fingerprint(hashes.SHA256()).hex().lower()
                except Exception:
                    continue
        except Exception:
            pass

    return "PLACEHOLDER_REPLACE_WITH_YOUR_CERT_SHA256"


CERT_SHA256 = resolve_cert_sha256()
ADDON_CLIENT_SECRET = resolve_env("ADDON_CLIENT_SECRET")

if not ADDON_CLIENT_SECRET:
    print("WARNING: ADDON_CLIENT_SECRET not set. Addon client lock will be empty.")


def derive_keystream(cert_sha256_hex: str, salt: bytes, length: int) -> bytes:
    if not cert_sha256_hex or "PLACEHOLDER" in cert_sha256_hex:
        key_bytes = hashlib.sha256(b"BHAVYA_DEV_FALLBACK_KEY").digest()
    else:
        try:
            key_bytes = bytes.fromhex(cert_sha256_hex)
        except Exception:
            key_bytes = hashlib.sha256(cert_sha256_hex.encode("utf-8")).digest()

    out = bytearray()
    counter = 0
    while len(out) < length:
        block = hmac.new(key_bytes, salt + counter.to_bytes(4, "big"), hashlib.sha256).digest()
        out.extend(block)
        counter += 1
    return bytes(out[:length])


salt = os.urandom(16)
secret_bytes = ADDON_CLIENT_SECRET.encode("utf-8") if ADDON_CLIENT_SECRET else b""
keystream = derive_keystream(CERT_SHA256, salt, len(secret_bytes)) if secret_bytes else b""
ciphertext = bytes(b ^ k for b, k in zip(secret_bytes, keystream))


def generate_fragments(data: bytes, num_fragments: int = 8) -> list:
    if not data:
        return []
    chunk_size = max(1, len(data) // num_fragments)
    fragments = []
    for i in range(0, len(data), chunk_size):
        chunk = data[i:i + chunk_size]
        mask = random.randint(0x10, 0xFE)
        xored = [b ^ mask for b in chunk]
        fragments.append((xored, mask, len(chunk)))
    return fragments


client_secret_fragments = generate_fragments(ciphertext)

# Generate header
lines = []
lines.append("// AUTO-GENERATED — DO NOT COMMIT TO VERSION CONTROL")
lines.append("// Generated by tools/generate_native_secrets.py")
lines.append("#pragma once")
lines.append("#include <cstdint>")
lines.append("#include <cstddef>")
lines.append("")
lines.append(f'constexpr char EXPECTED_CERT_PREFIX[] = "{CERT_SHA256}";')
lines.append("")

# Salt definition
salt_hex = ",".join(f"0x{b:02X}" for b in salt)
lines.append(f"static const uint8_t CLIENT_SECRET_SALT[16] = {{{salt_hex}}};")
lines.append(f"static constexpr size_t CLIENT_SECRET_TOTAL_LEN = {len(secret_bytes)};")
lines.append(f"static constexpr int CLIENT_SECRET_FRAGMENT_COUNT = {len(client_secret_fragments)};")
lines.append("")

for i, (xored_bytes, mask, length) in enumerate(client_secret_fragments):
    hex_vals = ",".join(f"0x{b:02X}" for b in xored_bytes)
    lines.append(f"static const uint8_t CS{i}[] = {{{hex_vals}}};")
lines.append("")

lines.append("struct Fragment {")
lines.append("    const uint8_t* data;")
lines.append("    uint8_t        len;")
lines.append("    uint8_t        mask;")
lines.append("};")
lines.append("")
lines.append("static const Fragment CLIENT_SECRET_FRAGMENTS[] = {")
for i, (xored_bytes, mask, length) in enumerate(client_secret_fragments):
    lines.append(f"    {{CS{i}, {length}, 0x{mask:02X}}},")
lines.append("};")
lines.append("")

header_content = "\n".join(lines) + "\n"

out_path = os.path.join("app", "src", "main", "cpp", "SecretsBridge_generated.h")
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    f.write(header_content)

print(f"Generated {out_path}")
print(f"  Client secret: {'[' + str(len(ADDON_CLIENT_SECRET)) + ' chars, encrypted]' if ADDON_CLIENT_SECRET else '[EMPTY]'}")
print(f"  Fragments: {len(client_secret_fragments)} client_secret (keystore-bound)")
print(f"  Cert SHA256: {CERT_SHA256[:20]}... (enforced)")

# Verify decryption roundtrip
if secret_bytes:
    recon_cipher = bytearray()
    for xored_bytes, mask, _ in client_secret_fragments:
        for b in xored_bytes:
            recon_cipher.append(b ^ mask)
    recon_keystream = derive_keystream(CERT_SHA256, salt, len(recon_cipher))
    recon_secret = bytes(b ^ k for b, k in zip(recon_cipher, recon_keystream)).decode("utf-8")
    assert recon_secret == ADDON_CLIENT_SECRET, "Client secret roundtrip mismatch"
    print("  Keystore-bound verification: PASS")
